name: YAML Substitution Example

on:
  workflow_dispatch:

jobs:
  yaml-substitution-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: debug
        run: ls
    
      - uses: microsoft/variable-substitution@v1
        with:
          files: './variables.yml'
        env:
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - run: |
          cat variables.yml
